spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive_db
    r2db:
      postgres:
        host: localhost
        port: 5432
        database: reactive_db
        username: postgres
        password: postgres
